name: dns_client
description: Dart implementation of DNS-over-HTTPS.
version: 0.2.1
homepage: https://github.com/dietfriends/dns_client

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.7
  json_serializable: ^6.5.3
  build_runner: ^2.3.2
  freezed: ^2.2.0
